name: JSDoc Build and Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build JSDoc and push to github
      run: |
        npm install
        npm run docs --if-present
        cd docs
        git init
      env:
        CI: true
    - uses: ad-m/github-push-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
