name: JSDoc Build and Push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build JSDoc
      run: |
        npm install
        npm run docs --if-present
        cd out
        git init
        git config user.email "wrscr.surpertop@gmail.com"
        git config user.name "Mattx8y"
        git remote add origin https://github.com/Mattx8y/Nameless-API-JS.git
        git add .
        git commit -m "Build JSDoc"
      env:
        CI: true
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
