name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run docs --if-present
        git config user.email "wrscr.surpertop@gmail.com"
        git config user.name "Mattx8y"
        git add ./docs/
        git commit -m "JSDoc"
        git push
      env:
        CI: true
